include:
  - project: "GNOME/citemplates"
    file: "templates/default-rules.yml"
  - project: 'GNOME/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-flatpak"
  - component: "gitlab.gnome.org/gnome/citemplates/gnomeos-basic-ci@master"
    inputs:
      grcov-c-options: '--ignore "tests/*"'
      gobject-linter: enabled

variables:
  APP_ID: 'io.github.steeb_k.Post'
  BUNDLE: 'io.github.steeb_k.Post.flatpak'
  FLATPAK_MODULE: 'post-mail'
  MANIFEST_PATH: 'io.github.steeb_k.Post.json'
  RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'

stages:
  - check
  - build
  - analysis
  - deploy

check-code-style:
  image: fedora:latest
  stage: 'check'
  before_script:
    - dnf install -y colordiff diffutils python3 uncrustify blueprint-compiler
  script:
    - bash data/check-code-style

codespell:
  image: fedora:latest
  stage: 'check'
  before_script:
    - dnf install -y codespell
  script:
    - codespell src -L crate -S "*.png,*.po,.git,*.jpg,eff_large_wordlist.txt,.mypy_cache,_build,gcal" -f

build-flatpak:
  extends: '.flatpak@x86_64'
  stage: build
  before_script: []

build-flatpak-aarch64:
  extends: '.flatpak@aarch64'
  stage: build
  before_script: []
  when: manual

scan-build-gate:
  stage: analysis
  image:
    name: fedora:latest
  needs:
    - job: "build-gnomeos-scan-build"
      artifacts: true
  script:
    - |
      if find _builddir/meson-logs/scanbuild -mindepth 1 -name 'index.html' -print -quit | grep -q .; then
        echo "scan-build has finidings - watch Scanbuild Report'"
        exit 1
      fi
      echo "scan-build: Good"

nightly:
  extends: '.publish_nightly'
  needs: ['build-flatpak']

nightly-aarch64:
  extends: '.publish_nightly'
  needs: ['build-flatpak-aarch64']
  when: manual

pages:
  stage: deploy
  needs: [ "build-gnomeos-grcov-c", "build-gnomeos-scan-build" ]
  script:
    - mkdir -p public
    - cp .gitlab-ci/landing-page.html public/index.html
    - mv public_scanbuild/ public/scanbuild
    - mv public_grcov/cobertura.xml public/
    - mv public_grcov/html public/coverage
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: ($CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH)