image: fedora:latest

stages:
- check
- lint

sast:
  stage: check
include:
- template: Security/SAST.gitlab-ci.yml

goblint:
  stage: lint
  allow_failure: true
  image:
    name: "ghcr.io/bilelmoussaoui/goblint:latest"
    entrypoint: [""]
  script:
    # Only available in Enterprise Edition
    - goblint --format sarif > goblint.sarif
    # Available in the Community Edition
    - goblint --format gitlab-codequality > goblint-codequality.json
  artifacts:
    expire_in: "1 week"
    reports:
      # Only available in Enterprise Edition
      sarif: goblint.sarif
      # Available in the Community Edition
      codequality: goblint-codequality.json

codespell:
  stage: check
  script:
    - dnf install -y codespell
    - codespell src -L crate -S "*.png,*.po,.git,*.jpg,eff_large_wordlist.txt,.mypy_cache,_build" -f

check-code-style:
  stage: check
  script:
    - dnf install -y uncrustify diff blueprint-compiler
    - bash data/check-code-style
  artifacts:
    when: on_failure
