types_headers = [
  'views/contact/contact-list/stamp-contact-list.h'
]

enums = gnome.mkenums_simple('stamp-type-builtins',
  sources: types_headers
)

stamp_sources = [
  'main.c',
  'stamp-application.c',
  'stamp-preferences.c',
  'stamp-preferences-signatures.c',
  'stamp-settings.c',
  'stamp-time-helpers.c',
  'stamp-webview.c',
  'stamp-window.c',
  'backend/stamp-session.c',
  'backend/stamp-account.c',
  'backend/stamp-bimi.c',
  'backend/stamp-helper.c',
  'backend/stamp-mime-parser.c',
  'backend/stamp-photo-cache.c',
  'backend/stamp-signature.c',
  'views/stamp-header-bar.c',
  'views/stamp-item.c',
  'views/stamp-tag.c',
  'views/calendar/stamp-calendar-view.c',
  'views/calendar/week-view/stamp-range.c',
  'views/calendar/week-view/stamp-range-tree.c',
  'views/calendar/week-view/stamp-week-grid.c',
  'views/calendar/week-view/stamp-week-header.c',
  'views/calendar/week-view/stamp-week-hour-bar.c',
  'views/calendar/week-view/stamp-week-view.c',
  'views/contact/stamp-contact-details.c',
  'views/contact/stamp-contact-view.c',
  'views/contact/contact-list/stamp-contact-item.c',
  'views/contact/contact-list/stamp-contact-list.c',
  'views/contact/contact-list/stamp-contact-list-store.c',
  'views/contact/contact-list/stamp-contact-row.c',
  'views/contact/book-list/stamp-book-account-item.c',
  'views/contact/book-list/stamp-book-item.c',
  'views/contact/book-list/stamp-book-list.c',
  'views/contact/book-list/stamp-book-row.c',
  'views/mail/stamp-mail-view.c',
  'views/mail/conversation-list/stamp-conversation-item.c',
  'views/mail/conversation-list/stamp-conversation-list.c',
  'views/mail/conversation-list/stamp-conversation-list-store.c',
  'views/mail/conversation-list/stamp-conversation-row.c',
  'views/mail/composer/stamp-composer.c',
  'views/mail/composer/stamp-contact-completion.c',
  'views/mail/folder-list/stamp-account-item.c',
  'views/mail/folder-list/stamp-folder-item.c',
  'views/mail/folder-list/stamp-folder-list.c',
  'views/mail/folder-list/stamp-folder-row.c',
  'views/mail/message-list/stamp-attachment-button.c',
  'views/mail/message-list/stamp-message-list.c',
  'views/mail/message-list/stamp-message-list-item.c',
  'views/mail/message-list/stamp-message-header.c',
  enums,
]

blueprints = custom_target('blueprints',
  input: files(
    'shortcuts-dialog.blp',
    'stamp-preferences.blp',
    'stamp-preferences-signatures.blp',
    'stamp-window.blp',
    'views/stamp-header-bar.blp',
    'views/stamp-tag.blp',
    'views/calendar/stamp-calendar-view.blp',
    'views/calendar/week-view/stamp-week-header.blp',
    'views/calendar/week-view/stamp-week-view.blp',
    'views/contact/stamp-contact-details.blp',
    'views/contact/stamp-contact-view.blp',
    'views/contact/contact-list/stamp-contact-list.blp',
    'views/contact/contact-list/stamp-contact-row.blp',
    'views/contact/book-list/stamp-book-list.blp',
    'views/contact/book-list/stamp-book-row.blp',
    'views/mail/stamp-mail-view.blp',
    'views/mail/conversation-list/stamp-conversation-list.blp',
    'views/mail/conversation-list/stamp-conversation-row.blp',
    'views/mail/composer/stamp-composer.blp',
    'views/mail/composer/stamp-contact-completion.blp',
    'views/mail/folder-list/stamp-folder-list.blp',
    'views/mail/folder-list/stamp-folder-row.blp',
    'views/mail/message-list/stamp-attachment-button.blp',
    'views/mail/message-list/stamp-message-header.blp',
    'views/mail/message-list/stamp-message-list.blp',
    'views/mail/message-list/stamp-message-list-item.blp',
  ),
  output: '.',
  command: [find_program('blueprint-compiler'), 'batch-compile', '@OUTPUT@', '@CURRENT_SOURCE_DIR@', '@INPUT@'],
)

stamp_deps = [
  dependency('gtk4'),
  dependency('libadwaita-1', version: '>= 1.4'),
  dependency('camel-1.2', version: '>= 3.28'),
  dependency('gsettings-desktop-schemas'),
  dependency('gstreamer-1.0'),
  dependency('libsoup-3.0'),
  dependency('libedataserver-1.2'),
  dependency('libedataserverui4-1.0'),
  dependency('libebook-1.2'),
  dependency('libedata-book-1.2'),
  dependency('libebook-contacts-1.2'),
  dependency('libportal-gtk4', version: '>= 0.6'),
  dependency('nss'),
  dependency('webkitgtk-6.0'),
  cc.find_library('resolv'),
  cc.find_library('m')
]

stamp_sources += gnome.compile_resources('stamp-resources',
  'stamp.gresource.xml',
  c_name: 'stamp',
  dependencies: blueprints,
)

stamp_includes = include_directories(
 '.',
 'backend',
 'views',
 'views/calendar',
 'views/calendar/week-view',
 'views/contact',
 'views/contact/book-list',
 'views/contact/contact-list',
 'views/mail',
 'views/mail/composer',
 'views/mail/folder-list',
 'views/mail/conversation-list',
 'views/mail/message-list',
)

executable('stamp', stamp_sources,
  dependencies: stamp_deps,
  include_directories: stamp_includes,
       install: true,
)

subdir('web-process-extension')